application: 0lvins-experements
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
 
- url: /stylesheets
  static_dir: stylesheets
 
- url: /.*
  script: portal.py
